# This file is being migrated to librarian@latest, and is no longer maintained by hand.

global_files_allowlist:
  - path: internal/generated/snippets/go.mod
    permissions: read-write
  - path: CHANGES.md
    permissions: read-write
libraries:
  - id: auth
    release_blocked: true
  - id: auditmanager
    release_blocked: true
  - id: auth/oauth2adapt
    release_blocked: true
  - id: bigtable
    release_blocked: true
  - id: bigquery
    release_blocked: true
  - id: bigquery/v2
    release_blocked: true
  - id: compute/metadata
    release_blocked: true
  - id: datastore
    release_blocked: true
  - id: firestore
    release_blocked: true
  - id: pubsub
    release_blocked: true
  - id: pubsub/v2
    release_blocked: true
  - id: pubsublite
    release_blocked: true
  - id: root-module
    release_blocked: true
  - id: spanner
    release_blocked: true
  - id: storage
    release_blocked: true
  - id: vertexai
    release_blocked: true
  - generate_blocked: true
    id: iap
